name: Package Install Stress Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  install-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4, 8.5]

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mbstring, bcmath, intl

      - name: Run install loop (stress test)
        run: |
          set +e

          for i in {1..10}
          do
            echo "=============================="
            echo "PHP ${{ matrix.php }} | Run #$i"
            echo "=============================="

            # Composer create project
            composer create-project ghostcompiler/laravel-react-jsx-boilerplate test-app-$i --no-interaction --prefer-dist || echo "create-project failed"

            cd test-app-$i || continue

            # Require packages
            composer require ghostcompiler/laravel-hetzner-robot  --no-interaction --prefer-dist || echo "robot failed"
            composer require ghostcompiler/laravel-hetzner-storagebox  --no-interaction --prefer-dist || echo "robot failed"
            composer require ghostcompiler/laravel-hetzner-cloud  --no-interaction --prefer-dist || echo "robot failed"
            composer require ghostcompiler/laravel-querybuilder  --no-interaction --prefer-dist || echo "robot failed"
            composer require ghostcompiler/laravel-model-caching  --no-interaction --prefer-dist || echo "robot failed"
            composer require ghostcompiler/laravel-uploads  --no-interaction --prefer-dist || echo "robot failed"

            composer create-project ghostcompiler/laravel-react-jsx-starter-kit my-app1 --no-interaction --prefer-dist || echo "starter-kit failed"
            composer create-project ghostcompiler/laravel-react-jsx-boilerplate my-app2 --no-interaction --prefer-dist || echo "starter-kit failed"


            cd ..
            echo "Updating repositories..."

            # Cleanup
            rm -rf test-app-$i || true

          done
